### ISSUE TITLE
Comand "composer start"  is not defined

### ISSUE THREAD

**Issue by DimitriMiranda** [LacunaSoftware/PkiSuiteSamples#2]
I did the clone of the project  I run composer install and after I run composer start
then the response the error  Command "start" is not defined. 
project RestPkiPhpClient.

**Comment by ismaelmedeiros** [comment]
Hello Dimitri!

You said that the project, that you are trying to run, is RestPkiPhpClient, but this project is our client library, it is not a application.

Can you confirm this for me? Which of the following projects are you trying to run?
- RestPkiPhpClient ([link](https://github.com/LacunaSoftware/RestPkiPhpClient))
- Sample Project for PHP ([link](https://github.com/LacunaSoftware/PkiSuiteSamples/tree/master/php/plain))

**Comment by DimitriMiranda** [comment]
Hello Ismael, 

I did a clone from https://github.com/LacunaSoftware/RestPkiPhpClient.git 
and follow the flow that was written on README.md 
But not worked. 

I work on a Brazilian public company and we would like to do a test on your tool

if you can, add me on hangout dimitri.miranda@defensoria.ba.def.br

Thanks!

**Comment by ismaelmedeiros** [comment]
This is the wrong repository. The repo [RestPkiPhpClient](https://github.com/LacunaSoftware/RestPkiPhpClient) is our client library published on [Packagist](https://packagist.org/packages/lacuna/restpki-client), and should not work with ```composer start```. The repository that uses this library is [PkiSuiteSamples](https://github.com/LacunaSoftware/PkiSuiteSamples).

You should clone from https://github.com/LacunaSoftware/PkiSuiteSamples.git. This is our samples repository in different languages. The PHP sample project is located on ```<root>/php/plain``` folder. 

At the project's root folder, you should run that commands: ```composer install``` and ```composer start``` to run the application.

In the case you need help, I'm adding you on Hangouts.
