### ISSUE TITLE
Define private authority root as trusted

### ISSUE THREAD

**Issue by CauanCabral** [LacunaSoftware/PkiSuiteSamples#6]
Theres a way to define a private authority root certificate as trusted?

I saw a sample on [PKI SDK about that](https://docs.lacunasoftware.com/pt-br/articles/pki-sdk/certificates/validation.html), but nothing on PKI Express (I'm looking for PHP SDK version).

**Comment by ismaelmedeiros** [comment]
Hello @CauanCabral!

In our PHP sample, the trusted authority roots are configured on the [config.php](https://github.com/LacunaSoftware/PkiSuiteSamples/blob/master/php/plain/config.php#L62) file. For this configuration to work out, it expected that the trusted roots are stored in the [resources/](https://github.com/LacunaSoftware/PkiSuiteSamples/tree/master/php/plain/resources) folder of the project.

This configuration is just a way to help to execute the sample more easily, but if you want to inform the trusted root certificate in your application, you have to do the same that the method [setPkiDefaults()](https://github.com/LacunaSoftware/PkiSuiteSamples/blob/master/php/plain/Util.php#L72) does on Util.php file, which is calling addTrustedRoot() with the path of the trusted root certificate. Each one of the classes in the PKI Express library that does an operation (signature, validation, ...) have that method in common.

**Comment by CauanCabral** [comment]
Thanks @ismaelmedeiros  

I had forgot the `config.php` file from resources path.
