### ISSUE TITLE
does not work with fedora 36

### ISSUE THREAD

**Issue by gustvao** [LacunaSoftware/PkiSuiteSamples#69]
Guys, it used to work.

But no matter what browser I try, chrome or firefox, after adding the extensions and instaling the .RPM package in my fedora I cannot move pass the setup screen https://get.webpkiplugin.com/Setup?brand=&jslib=&browser=Chrome&returnUrl=

Must be a bug.

Can you pls assist?

Tks

**Comment by Jonas97salatiel** [comment]
Prezados, 

Identifiquei a mesma falha, porém no windows. A instalação do Web PKI na máquina sempre falha, e o instalador retorna o seguinte erro.
 
![image](https://user-images.githubusercontent.com/38478074/176757243-28089efa-d558-4818-acf1-feb30e8f18be.png)
 
Desde já agradeço pelo apoio.

**Comment by brunocapu** [comment]
Olá @Jonas97salatiel
Acredito que não tem relação com o Fedora. Este é um erro do instalador MSI ao acessar o diretório temporário do Windows.
Por favor veja nossa FAQ como solucionar:
https://lacuna.movidesk.com/kb/article/167963/erro-de-instalacao-2502-2503

Para novos suportes, por favor também use o nosso canal oficial de suporte:
https://lacuna.movidesk.com
Obrigado.
Abs

**Comment by brunocapu** [comment]
Ok @gustvao 
We are checking this issue.

**Comment by brunocapu** [comment]
@gustvao We've just released a new version of WebPKI RPM package with a fix. Please try to install it and run again.
On any other problem please contact us on the official user support channel:
https://lacuna.movidesk.com/

At your disposal
